name: fanoos_project
description: A new Flutter package.
version: 0.0.6+1
homepage: https://github.com/ali2236/fanoos_project

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: